name: ci

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: '1.25.x'
          cache: true
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '22.21.0'
          cache: npm
          cache-dependency-path: webmanager/package-lock.json
      - run: make production
